name: json_helpers
version: 0.1.5
description: The `json_helpers` contains functions that make it easier decoding JSON objects directly from strings, lists and maps.
homepage: https://github.com/mezoni/json_helpers
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:  
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
